In [1]:
import numpy as np

In [2]:
# 1.
vector = np.zeros((10, ), int)
vector.size

10

In [3]:
# 2.
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [13]:
# 3.
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# 4.
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [6]:
# 5.
data = np.arange(0,9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 6.
data = np.array([1,2,0,0,4,0], int)
condition =  data != 0
data[condition]

array([1, 2, 4])

In [8]:
# 7.
matrix = np.identity((3), int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [9]:
# 8.
matrix = np.random.randn(3,3)
matrix

array([[-0.81412052,  0.60866167,  0.76681343],
       [-0.48349977, -0.03323256, -0.5311564 ],
       [-0.73419134, -1.83550222, -0.78769905]])

In [10]:
# 9.
print(matrix.max())
print(matrix.min())


0.7668134299101407
-1.835502215842258


In [17]:
matrix[np.argmax(matrix) //3 , np.argmax(matrix)%3], np.argmax(matrix)

(0.7668134299101407, 2)

In [18]:
matrix[np.argmin(matrix) //3 , np.argmin(matrix)%3], np.argmin(matrix)

(-1.835502215842258, 7)

In [11]:
# 10.
print(matrix.mean(axis=1))
print(matrix.mean(axis=0))

[ 0.18711819 -0.34929625 -1.11913087]
[-0.67727054 -0.42002437 -0.18401401]
