In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
from sklearn.model_selection import train_test_split

D:\Users\Administrator\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Users\Administrator\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
array1 = np.array([1,2,3])

In [4]:
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [6]:
array2 = np.array([[1,2,3], [4,5,6]])
print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [7]:
array3 = np.array([[[1,2,3]]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 1, 3)


In [8]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  3차원


In [10]:
list1 =[1,2,3]
print(type(list1))
array4 = np.array(list1)
print(type(array4))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float32')

In [16]:
print(array_float, array_float.dtype)

[1. 2. 3.] float32


In [17]:
array1 = np.arange(10)

In [18]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
array1.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
array1.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
array1 = np.arange(16)
array3d = array1.reshape(-1,2,2, 2)
array3d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [33]:
array3d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
array1 = np.arange(start = 1, stop = 10)
array1[2]

3

In [37]:
array1d = array1.reshape(3,3)

In [40]:
array1d[0, 1]

2

In [44]:
print(array1d[0:2, 0:1])

[[1]
 [4]]


In [48]:
array1d[[0,1,2], 2]
array1d[[0,1,2], 2].tolist()

[3, 6, 9]

In [50]:
array1d[array1d>5]

array([6, 7, 8, 9])

In [52]:
bool_array = [False,False,False,False,False,True,True,True,True ]
array2 = array1[bool_array]
array2

array([6, 7, 8, 9])

In [53]:
indexs = np.array([5,6,7,8])
array3 = array1[indexs]
array3

array([6, 7, 8, 9])

In [81]:
name = np.array(['a','c','d','m','e'])
score = np.random.randint(75, 100, size=5)

In [82]:
score_index = np.argsort(score)[::-1]
print(np.sort(score))
print(score_index)
print(name[score_index])

[75 83 86 89 95]
[3 1 2 0 4]
['m' 'c' 'd' 'a' 'e']


In [57]:
A = np.array([[1,2,3],[4,5,6]])
B = np.arange(7,13).reshape(-1,2)

In [60]:
odt_product = np.dot(A,B)

In [61]:
odt_product

array([[ 58,  64],
       [139, 154]])

In [62]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])